# Blog info
blog_name: unagi
slogan: Think Big Act Small
url: https://millione.github.io

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords:

home_nav:
  - name: Blog
    url: /archives
    target_blank: false
  - name: Resume
    url: https://millione.github.io/resume
    target_blank: true
  - name: Github
    url: https://github.com/Millione
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 订阅
    url: /atom.xml
    target_blank: true # 在新页面打开

page_nav_style: CIRCLE # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|false

# 盒子
toolbox:
  isShow: true # true|false
  text: ···

# set backtop show or hide
backtop:
  home: true
  category: true
  tag: true
  post: true

post:
  header_align: CENTER # LEFT|CENTER
  showToc: false # true|false
  showComments: false
  open_in_new_window: false
  show_prev_next: true

# custom CSS style
personal_style: /css/personal-style.css

## custom theme
home_background_scheme: light # dark、light

# custom font-family
blog_name_font_familiy: calligraffittiregular

init_page_content: HOME_NAV # HOME_NAV | POST
